### ISSUE TITLE
Please add git tags for versions.

### ISSUE THREAD

**Issue by socketpair** [koutheir/binary-security-check#3]
I like something like git tag `v1.2.3`

**Comment by koutheir** [comment]
Why do you need a git tag?

Users are expected to use the versions published on `crates.io`.

**Comment by socketpair** [comment]
@koutheir
1. I need to make .rpm package and put sources to the .srpm. Good practice is to put sources with provided github URL where anyone can directly download the archive. i.e. `Source0: https://github.com/koutheir/binary-security-check/archive/%{commit}/%{name}-%{shortcommit}.tar.gz`. Now I have to specify hashtag instead of git tag.

2. Knowing what version correspond to what commit is very important thing.

**Comment by koutheir** [comment]
> Now I have to specify hashtag instead of git tag.

Nobody should suffer like that.

> Knowing what version correspond to what commit is very important thing.

That metadata is stored in `crates.io`, but there's no harm to also store it in git as tags.

I added tags for versions `1.0.0` to the latest version (currently `1.2.4`). I also verified that the URL to download the sources works with tag names.
